# Limpieza e integración del catálogo StreamView

## 1. Objetivo y alcance

Este notebook prepara las fuentes oficiales de **Movies** y **TV Shows** mediante carga, revisión estructural, limpieza, normalización, homologación, integración, validación y exportación. El resultado se guarda en `data/processed/catalogo_streamview.csv` y servirá como fuente para etapas posteriores de análisis y visualización en Looker Studio.

## Diccionario de variables

Las etiquetas sugeridas están pensadas para títulos de gráficos, ejes, leyendas y tablas. El catálogo final conserva los nombres técnicos en inglés para mantener compatibilidad con las fuentes y el EDA.

| Variable | Nombre claro para gráficos | Descripción e interpretación |
|---|---|---|
| `type` | Tipo de contenido | Indica si el registro corresponde a una película (`Movie`) o a una serie (`TV Show`). Conviene traducir los valores al español al presentarlos: **Película** y **Serie**. |
| `title` | Título | Nombre del contenido. Útil para rankings y etiquetas de elementos individuales. |
| `director` | Dirección | Nombre o nombres de las personas directoras asociados al contenido. Puede contener varios valores. |
| `cast` | Reparto | Intérpretes asociados al contenido. Puede contener varios valores; no representa el orden de importancia del reparto tras la normalización actual. |
| `country` | Países asociados | País o países asociados al contenido según la fuente. Puede contener varios valores; no asumir que representa una única región. |
| `date_added` | Fecha de incorporación al catálogo | Fecha en que el contenido fue añadido al catálogo de la fuente. Sirve para analizar incorporaciones, no el estreno. |
| `release_year` | Año de estreno | Año de lanzamiento original del contenido, según la fuente. |
| `rating` | Puntuación del título | Puntuación numérica reportada por la fuente, en una escala observada de 0 a 10. Revisar su relación con `vote_average` antes de graficar ambas variables juntas. |
| `genres` | Géneros | Género o géneros asociados al contenido. Un título puede pertenecer a más de un género. |
| `language` | Idioma (código) | Código del idioma asociado al contenido, por ejemplo `en`. Traducir o convertir los códigos a nombres legibles antes de usarlos como etiquetas. |
| `popularity` | Índice de popularidad | Índice relativo de popularidad de la fuente. No equivale a reproducciones, visualizaciones ni cantidad de usuarios. |
| `vote_count` | Cantidad de votos | Número de votos que respalda la valoración disponible. Ayuda a contextualizar la cantidad de observaciones, no la calidad por sí sola. |
| `vote_average` | Valoración promedio | Promedio de las valoraciones registradas para el contenido, en una escala observada de 0 a 10. No representa la cantidad de votos. |
| `budget` | Presupuesto reportado | Presupuesto asociado a películas. En series no aplica y se conserva como dato faltante; confirmar la moneda en la documentación de la fuente antes de mostrarla. |
| `revenue` | Ingresos reportados | Ingresos asociados a películas. En series no aplica y se conserva como dato faltante; confirmar la moneda en la documentación de la fuente antes de mostrarla. |

**Notas para el diseño de gráficos:** `rating` y `vote_average` muestran puntuaciones en la misma escala y podrían ser redundantes; usar preferentemente `vote_average` para mantener consistencia con el EDA, salvo que se confirme una diferencia semántica. Los campos `director`, `cast`, `country` y `genres` contienen listas en una sola fila: al desglosarlos para un gráfico, evitar contar varias veces el mismo contenido. Los valores faltantes en `budget` y `revenue` no deben interpretarse como cero.

El catálogo analítico no incluye `show_id`, `duration` ni `description`; por tanto, no se describen como variables disponibles para los gráficos de este dataset.

Quedan fuera del alcance el análisis exploratorio de negocio, los gráficos, el storytelling, los dashboards, las conclusiones estratégicas y las recomendaciones.

## 2. Configuración y carga de fuentes

Las rutas se resuelven desde la estructura del proyecto, con independencia de si el notebook se ejecuta desde la raíz o desde `notebooks/`. Los hashes SHA-256 calculados al inicio se comparan al finalizar el procesamiento para comprobar que los archivos cargados no fueron modificados durante esta ejecución; no constituyen una comparación con hashes oficiales externos.

In [ ]:
import hashlib
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display


def find_project_root(start_path):
    # Localiza la raíz que contiene data/raw.
    start_path = Path(start_path).resolve()
    for candidate in (start_path, *start_path.parents):
        if (candidate / "data" / "raw").is_dir():
            return candidate
    raise FileNotFoundError("No se encontró la estructura data/raw del proyecto.")


def sha256_file(file_path, chunk_size=1024 * 1024):
    # Calcula el hash SHA-256 de un archivo sin modificarlo.
    digest = hashlib.sha256()
    with Path(file_path).open("rb") as file:
        for chunk in iter(lambda: file.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


project_root = find_project_root(Path.cwd())
raw_dir = project_root / "data" / "raw"
processed_dir = project_root / "data" / "processed"

movies_path = raw_dir / "netflix_movies_detailed_up_to_2025.csv"
tv_shows_path = raw_dir / "netflix_tv_shows_detailed_up_to_2025.csv"
output_path = processed_dir / "catalogo_streamview.csv"

source_paths = {"Movies": movies_path, "TV Shows": tv_shows_path}
source_hashes_initial = {
    source: sha256_file(path) for source, path in source_paths.items()
}

movies = pd.read_csv(movies_path)
tv_shows = pd.read_csv(tv_shows_path)

print(f"Raíz del proyecto: {project_root}")
print(f"Movies cargadas: {len(movies):,} filas")
print(f"TV Shows cargadas: {len(tv_shows):,} filas")

Raíz del proyecto: C:\Users\shein\OneDrive\Documentos\GitHub\visualizacion-de-datos-StreamView-Analytics
Movies cargadas: 16,000 filas
TV Shows cargadas: 16,000 filas

## 3. Revisión estructural inicial

La inspección se limita a las características necesarias para decidir la limpieza: dimensiones, columnas, tipos, nulos, diferencias de esquema y duplicados completos. No se realizan rankings ni interpretaciones de negocio.

In [ ]:
for column in ["budget", "revenue"]:
    if column not in tv_shows_clean.columns:
        tv_shows_clean[column] = pd.Series(
            np.nan, index=tv_shows_clean.index, dtype="float64"
        )

column_order = movies_clean.columns.tolist()
tv_shows_clean = tv_shows_clean.reindex(columns=column_order)

assert movies_clean.columns.tolist() == tv_shows_clean.columns.tolist()
assert tv_shows_clean[["budget", "revenue"]].isna().all().all()
assert tv_shows_clean[["budget", "revenue"]].to_numpy().dtype == object or (
    tv_shows_clean["budget"].dtype == "float64"
    and tv_shows_clean["revenue"].dtype == "float64"
)

print(f"Esquemas homologados: {len(column_order)} columnas por fuente")

Esquemas homologados: 18 columnas por fuente

## 4. Criterios de limpieza

Los valores faltantes reales se conservan como nulos. No se crean categorías como “Desconocido” o “No disponible” y no se realiza imputación estadística.

| Variable | Tratamiento |
|---|---|
| `description` | Eliminar después de la integración. |
| `show_id` | Eliminar porque es un identificador interno con duplicados y no aporta una dimensión analítica útil ni una métrica de negocio. |
| `duration` | Eliminar porque está casi completamente nula y, en la práctica, solo aporta una única categoría de duración para TV Shows, sin valor para segmentación ni comparación. |
| `country` | Mantener `NaN`; normalizar solamente el formato multivalor. |
| `genres` | Mantener `NaN`; normalizar solamente el formato multivalor, sin ordenar sus elementos. |
| `cast` | Mantener `NaN`; normalizar solamente espacios estructurales. |
| `director` | Mantener `NaN`; normalizar solamente espacios estructurales. |
| `budget` | Convertir 0 a `NaN`; aplicable únicamente a Movies. |
| `revenue` | Convertir 0 a `NaN`; aplicable únicamente a Movies. |

Solo se eliminan filas completamente idénticas. Los identificadores repetidos con información diferente no se resuelven automáticamente.

## 5. Limpieza y normalización de las fuentes

Las cadenas se recortan en sus extremos y las cadenas vacías se convierten en nulos. En las variables multivalor se uniforman únicamente los espacios alrededor de las comas, preservando el orden y el significado originales. Después se eliminan, si existen, duplicados de fila completa dentro de cada fuente.

In [ ]:
import re

MULTIVALUE_COLUMNS = ["cast", "director", "country", "genres"]


def normalize_multivalue(value):
    # El orden de los elementos no debe afectar la semántica del campo.
    if pd.isna(value):
        return np.nan

    tokens = [part.strip() for part in str(value).split(",") if part.strip()]
    tokens = [re.sub(r"\s+", " ", token).strip() for token in tokens]

    normalized = {}
    for token in tokens:
        normalized[token.casefold()] = token.strip().title()

    canonical = sorted(normalized.values(), key=lambda x: x.casefold())
    return ", ".join(canonical) if canonical else np.nan


def clean_source(dataframe):
    # Aplica únicamente transformaciones estructurales permitidas.
    cleaned = dataframe.copy()
    text_columns = cleaned.select_dtypes(include=["object", "string"]).columns

    for column in text_columns:
        cleaned[column] = cleaned[column].astype(object).str.strip()
        cleaned[column] = cleaned[column].replace("", np.nan)

    for column in MULTIVALUE_COLUMNS:
        if column in cleaned.columns:
            cleaned[column] = cleaned[column].map(normalize_multivalue).astype(object)

    duplicate_count = int(cleaned.duplicated().sum())
    cleaned = cleaned.drop_duplicates().reset_index(drop=True)
    return cleaned, duplicate_count


movies_clean, movie_duplicates_removed = clean_source(movies)
tv_shows_clean, tv_duplicates_removed = clean_source(tv_shows)

print(f"Duplicados completos eliminados de Movies: {movie_duplicates_removed}")
print(f"Duplicados completos eliminados de TV Shows: {tv_duplicates_removed}")
print(f"Filas limpias de Movies: {len(movies_clean):,}")
print(f"Filas limpias de TV Shows: {len(tv_shows_clean):,}")

Duplicados completos eliminados de Movies: 0
Duplicados completos eliminados de TV Shows: 0
Filas limpias de Movies: 16,000
Filas limpias de TV Shows: 16,000

## 6. Homologación de esquemas

`budget` y `revenue` son variables exclusivas de Movies. Se incorporan a TV Shows como columnas completamente nulas y luego se aplica el mismo orden de columnas a ambas fuentes antes de concatenarlas.

In [ ]:
for column in ["budget", "revenue"]:
    if column not in tv_shows_clean.columns:
        tv_shows_clean[column] = pd.Series(
            np.nan, index=tv_shows_clean.index, dtype="float64"
        )

column_order = movies_clean.columns.tolist()
tv_shows_clean = tv_shows_clean.reindex(columns=column_order)

assert movies_clean.columns.tolist() == tv_shows_clean.columns.tolist()
assert tv_shows_clean[["budget", "revenue"]].isna().all().all()
assert all(
    isinstance(value, (float, np.floating)) and np.isnan(value)
    for value in tv_shows_clean[["budget", "revenue"]].to_numpy(dtype=object).ravel()
)

print(f"Esquemas homologados: {len(column_order)} columnas por fuente; finanzas no aplican a series.")

Esquemas homologados: 18 columnas por fuente; finanzas no aplican a series.

## 7. Integración

Movies y TV Shows se integran mediante concatenación vertical. No se emplean `join` ni `merge`, por lo que se mantiene la granularidad de las fuentes: cada registro de entrada aporta una fila al catálogo. Las columnas `description`, `show_id` y `duration` se eliminan después de la unión porque no aportan valor analítico útil: `description` es texto redundante, `show_id` tiene duplicados y no es una clave de negocio confiable, y `duration` casi no tiene información útil y está mayormente nula.

In [ ]:
catalogo = pd.concat([movies_clean, tv_shows_clean], ignore_index=True)
catalogo = catalogo.drop(columns=["description", "show_id", "duration"])

print(f"Catálogo integrado: {catalogo.shape[0]:,} filas y {catalogo.shape[1]} columnas")

Catálogo integrado: 32,000 filas y 15 columnas

## 8. Transformaciones finales

Los tipos se normalizan sobre el catálogo integrado. `show_id` y `duration` ya fueron retirados para evitar variables casi vacías o no analíticas. La conversión de `date_added` conserva los nulos preexistentes y se detiene si aparecen nulos nuevos. En `budget` y `revenue`, los ceros se interpretan como información financiera no disponible según la regla del proyecto y se convierten en nulos.

In [ ]:
text_columns = [
    "type", "title", "director", "cast", "country",
    "genres", "language",
]
integer_columns = ["release_year", "vote_count"]
float_columns = ["rating", "popularity", "vote_average"]
financial_columns = ["budget", "revenue"]

for column in text_columns:
    catalogo[column] = catalogo[column].astype(object)

date_nulls_before = int(catalogo["date_added"].isna().sum())
converted_dates = pd.to_datetime(
    catalogo["date_added"], format="%Y-%m-%d", errors="coerce"
)
date_nulls_after = int(converted_dates.isna().sum())
unexpected_date_nulls = date_nulls_after - date_nulls_before
assert unexpected_date_nulls == 0, (
    f"La conversión de date_added introdujo {unexpected_date_nulls} nulos."
)
if converted_dates.isna().any():
    catalogo["date_added"] = converted_dates.astype(object).where(
        converted_dates.notna(), np.nan
    )
else:
    catalogo["date_added"] = converted_dates

for column in integer_columns:
    numeric_values = pd.to_numeric(catalogo[column], errors="raise")
    if numeric_values.isna().any():
        catalogo[column] = numeric_values.map(
            lambda value: int(value) if pd.notna(value) else np.nan
        ).astype(object)
    else:
        catalogo[column] = numeric_values.astype("int64")

for column in float_columns + financial_columns:
    catalogo[column] = pd.to_numeric(
        catalogo[column], errors="raise"
    ).astype("float64")

for column in financial_columns:
    catalogo[column] = catalogo[column].replace(0, np.nan)

for column in catalogo.columns:
    null_values = catalogo.loc[catalogo[column].isna(), column].to_numpy(dtype=object)
    assert all(
        isinstance(value, (float, np.floating)) and np.isnan(value)
        for value in null_values
    ), f"La columna {column} contiene nulos distintos de NaN de NumPy."

print(f"Nulos nuevos por conversión de date_added: {unexpected_date_nulls}")
print("Todos los faltantes del catálogo están representados como NaN de NumPy.")

Nulos nuevos por conversión de date_added: 0
Todos los faltantes del catálogo están representados como NaN de NumPy.

## 9. Validación integral

Las comprobaciones siguientes centralizan las reglas de volumen, esquema, granularidad, tipos, nulos y restricciones financieras. La búsqueda de representaciones artificiales de ausencia compara el valor completo después de aplicar `strip()` y `casefold()`; no utiliza búsquedas por subcadena, por lo que valores válidos como `Sci-Fi` no producen falsos positivos. Además, se eliminan previamente `show_id` y `duration` porque no aportan una variable analítica útil: el primero presenta duplicados y el segundo concentra casi toda la información faltante y apenas varía en el conjunto final.

In [ ]:
expected_columns = [
    "type", "title", "director", "cast", "country",
    "date_added", "release_year", "rating", "genres",
    "language", "popularity", "vote_count", "vote_average",
    "budget", "revenue",
]
expected_type_counts = {"Movie": 16_000, "TV Show": 16_000}
artificial_na_tokens = {
    "n/a", "no disponible", "desconocido", "null", "none", "-"
}
artificial_na_columns = ["genres", "cast", "director", "country"]

artificial_na_counts = {}
for column in artificial_na_columns:
    normalized_values = catalogo[column].dropna().str.strip().str.casefold()
    artificial_na_counts[column] = int(
        normalized_values.isin(artificial_na_tokens).sum()
    )

def missing_values_are_numpy_nan(dataframe):
    for column in dataframe.columns:
        null_values = dataframe.loc[dataframe[column].isna(), column].to_numpy(dtype=object)
        if not all(
            isinstance(value, (float, np.floating)) and np.isnan(value)
            for value in null_values
        ):
            return False
    return True


type_counts = catalogo["type"].value_counts().to_dict()
full_duplicates = int(catalogo.duplicated().sum())
source_hashes_current = {
    source: sha256_file(path) for source, path in source_paths.items()
}

assert catalogo.shape == (32_000, 15)
assert catalogo.columns.tolist() == expected_columns
assert "description" not in catalogo.columns
assert "show_id" not in catalogo.columns
assert "duration" not in catalogo.columns
assert type_counts == expected_type_counts
assert set(catalogo["type"].dropna().unique()) == {"Movie", "TV Show"}
assert full_duplicates == 0
assert int(catalogo["budget"].eq(0).sum()) == 0
assert int(catalogo["revenue"].eq(0).sum()) == 0
assert int(catalogo["budget"].isna().sum()) == 27_153
assert int(catalogo["revenue"].isna().sum()) == 26_355
assert catalogo.loc[
    catalogo["type"].eq("TV Show"), ["budget", "revenue"]
].isna().all().all()
assert str(catalogo["budget"].dtype) == "float64"
assert str(catalogo["revenue"].dtype) == "float64"
assert missing_values_are_numpy_nan(catalogo)
assert sum(artificial_na_counts.values()) == 0
assert source_hashes_current == source_hashes_initial

validation_summary = pd.Series(
    {
        "filas": len(catalogo),
        "columnas": catalogo.shape[1],
        "Movies": type_counts.get("Movie", 0),
        "TV Shows": type_counts.get("TV Show", 0),
        "duplicados completos": full_duplicates,
        "ceros en budget": int(catalogo["budget"].eq(0).sum()),
        "ceros en revenue": int(catalogo["revenue"].eq(0).sum()),
        "nulos en budget": int(catalogo["budget"].isna().sum()),
        "nulos en revenue": int(catalogo["revenue"].isna().sum()),
        "nulos NumPy NaN": missing_values_are_numpy_nan(catalogo),
        "tokens artificiales de nulo": sum(artificial_na_counts.values()),
    },
    name="resultado",
)

display(validation_summary.to_frame())
display(catalogo.isna().sum().rename("nulos").to_frame())
display(catalogo.dtypes.astype(str).rename("tipo").to_frame())
display(pd.Series(artificial_na_counts, name="coincidencias exactas").to_frame())

                            resultado
filas                           32000
columnas                           15
Movies                          16000
TV Shows                        16000
duplicados completos                0
ceros en budget                     0
ceros en revenue                    0
nulos en budget                 27153
nulos en revenue                26355
nulos NumPy NaN                  True
tokens artificiales de nulo         0

              nulos
type              0
title             0
director      11097
cast           1361
country        2263
date_added        0
release_year      0
rating            0
genres         1081
language          0
popularity        0
vote_count        0
vote_average      0
budget        27153
revenue       26355

                        tipo
type                  object
title                 object
director              object
cast                  object
country               object
date_added    datetime64[us]
release_year           int64
rating               float64
genres                object
language              object
popularity           float64
vote_count             int64
vote_average         float64
budget               float64
revenue              float64

          coincidencias exactas
genres                        0
cast                          0
director                      0
country                       0

No se conserva `show_id` porque no corresponde a una clave de negocio confiable: aparece repetido y no se puede distinguir filas duplicadas reales de registros distintos con el mismo identificador. La variable `duration` tampoco se mantiene porque casi no aporta información útil: la mayoría de valores son nulos y, para la parte no nula, no ofrece segmentación analítica relevante para el catálogo consolidado.

## 10. Exportación

Superadas las validaciones, `date_added` se representa como `YYYY-MM-DD` y el catálogo se exporta una sola vez al directorio de datos procesados. Los valores faltantes se escriben explícitamente como `NaN` mediante `na_rep="NaN"`, para que puedan recargarse como `np.nan`. No se generan versiones intermedias del dataset definitivo.

In [ ]:
processed_dir.mkdir(parents=True, exist_ok=True)

catalogo_export = catalogo.copy()
export_dates = pd.to_datetime(
    catalogo_export["date_added"], format="%Y-%m-%d", errors="raise"
)
formatted_dates = export_dates.dt.strftime("%Y-%m-%d").astype(object)
catalogo_export["date_added"] = formatted_dates.where(
    export_dates.notna(), np.nan
)
catalogo_export.to_csv(output_path, index=False, na_rep="NaN")

print(f"Archivo exportado con faltantes explícitos como NaN: {output_path}")

Archivo exportado con faltantes explícitos como NaN: C:\Users\shein\OneDrive\Documentos\GitHub\visualizacion-de-datos-StreamView-Analytics\data\processed\catalogo_streamview.csv

## 11. Verificación posterior a la exportación

El único archivo definitivo se vuelve a cargar con los tipos esperados. Se comprueban nuevamente dimensiones, columnas, tipos de contenido, duplicados completos, recuperación de fecha y numéricos, y las restricciones de `budget` y `revenue`.

In [ ]:
export_dtypes = {
    **{column: "object" for column in text_columns},
    **{
        column: "object" if catalogo[column].isna().any() else "int64"
        for column in integer_columns
    },
    **{column: "float64" for column in float_columns + financial_columns},
}
catalogo_verified = pd.read_csv(
    output_path,
    dtype=export_dtypes,
    keep_default_na=False,
    na_values=["NaN"],
)
verified_dates = pd.to_datetime(
    catalogo_verified["date_added"], format="%Y-%m-%d", errors="coerce"
)
assert verified_dates.isna().sum() == catalogo["date_added"].isna().sum()
if verified_dates.isna().any():
    catalogo_verified["date_added"] = verified_dates.astype(object).where(
        verified_dates.notna(), np.nan
    )
else:
    catalogo_verified["date_added"] = verified_dates

for column in integer_columns:
    numeric_values = pd.to_numeric(catalogo_verified[column], errors="raise")
    if numeric_values.isna().any():
        catalogo_verified[column] = numeric_values.map(
            lambda value: int(value) if pd.notna(value) else np.nan
        ).astype(object)
    else:
        catalogo_verified[column] = numeric_values.astype("int64")

assert catalogo_verified.shape == catalogo.shape
assert catalogo_verified.columns.tolist() == expected_columns
assert "show_id" not in catalogo_verified.columns
assert "duration" not in catalogo_verified.columns
assert catalogo_verified["type"].value_counts().to_dict() == expected_type_counts
assert set(catalogo_verified["type"].dropna().unique()) == {"Movie", "TV Show"}
assert int(catalogo_verified.duplicated().sum()) == 0
assert catalogo_verified.isna().sum().equals(catalogo.isna().sum())
assert missing_values_are_numpy_nan(catalogo_verified)
assert all(
    catalogo_verified[column].dtype == catalogo[column].dtype
    for column in integer_columns + float_columns + financial_columns
)
assert int(catalogo_verified["budget"].eq(0).sum()) == 0
assert int(catalogo_verified["revenue"].eq(0).sum()) == 0
assert int(catalogo_verified["budget"].isna().sum()) == 27_153
assert int(catalogo_verified["revenue"].isna().sum()) == 26_355
assert catalogo_verified.loc[
    catalogo_verified["type"].eq("TV Show"), ["budget", "revenue"]
].isna().all().all()

print(
    "Verificación posterior a la exportación superada: "
    f"{catalogo_verified.shape[0]:,} filas y {catalogo_verified.shape[1]} columnas; "
    "conteos de nulos conservados y representados como NaN de NumPy."
)

Verificación posterior a la exportación superada: 32,000 filas y 15 columnas; conteos de nulos conservados y representados como NaN de NumPy.

## Cierre

Las fuentes de Movies y TV Shows fueron preparadas e integradas de acuerdo con las reglas del proyecto. El catálogo resultante fue validado antes y después de su exportación, y `data/processed/catalogo_streamview.csv` queda preparado para las etapas posteriores de análisis y visualización en Looker Studio.

In [ ]:
import re


def normalize_multivalue_example(value):
    if pd.isna(value):
        return np.nan

    tokens = [part.strip() for part in str(value).split(",") if part.strip()]
    tokens = [re.sub(r"\s+", " ", token).strip() for token in tokens]

    normalized = {}
    for token in tokens:
        normalized[token.casefold()] = token.strip().title()

    canonical = sorted(normalized.values(), key=lambda x: x.casefold())
    return ", ".join(canonical) if canonical else np.nan


example = pd.Series([
    "Drama, Comedy",
    "Comedy, Drama",
    "Comedy, Comedy, Drama",
    "United States, Mexico",
    "Mexico, United States",
])
print(example.map(normalize_multivalue_example).to_list())

['Comedy, Drama', 'Comedy, Drama', 'Comedy, Drama', 'Mexico, United States', 'Mexico, United States']